### PR TITLE
Add HILT main board and basic I/O modules

### PR DESCRIPTION
**Pull request by BluCodeGH**
I procrastinated on exams by designing a hardware-in-the-loop tester for rocketcan boards, here it is!

The main idea is that there is a master board (the HILT) that connects to a computer over USB and just has a boatload of analog I/O pins. Those pins get broken out to 10 daughter boards (blades) that can then implement specific functionality like analog input, current measurement, digital I/O, etc. To run a test you can connect up the blades you need, plug all of the connectors on a board into the blades, and then a program on the computer can control and read from all the pins to verify functionality.

Currently I have a rough layout of the master HILT (if y'all have comments I'd really rather not route the 100tqfp twice) and two finalized blades:

The analog input blade is really a voltage rail monitor, it does voltage and current measurements of a line running through it. It can also disconnect that line to simulate connecting / disconnecting power sources.

The output blade has two modes - analog and digital. In analog mode it takes a PWM signal from the pic and smooths it to create a shitty DAC (since the PIC only has two DAC pins), and then puts it through an op amp to boost from 3V3 to 5V and for better output impedance. It also has a current monitor so it can act like a current source/sink by adjusting the output voltage to hit a desired current. In digital mode it is a simple MOSFET level shifter for higher speed 5V signals.

### CODE REVIEW

**Comment by Artem-Sotnikov** [comment]
Party board review comments:

- I2C pullups (maybe CS too)
- SSR on resistance (probably switch to conventional)
- Analog switch voltage range maybe too low
- Add grounds everywhere
- Quadruple check pinout on 'blades' (i.e. orientation)
- Add low pass filters on voltage reference & voltage sense
- Check GBW on op-amps
- Lower level shitter output impedance
- double check that the INA2181 is high-side/low-side
- double check resistance on current sense for analog/digital switch
- double check that all parts are still in stock
- add test points

**Comment by JasonBrave** [comment]
Question: Is pull-up CS line with resistor beside debug LED intentional?
Also a few mounting holes could be added for standoffs, so the board can be placed on desk without the IC touching the desk

**Comment by JasonBrave** [comment]
Also the date on the output board has to be updated, it's not 2022 anymore

**Comment by BluCodeGH** [comment]
- The CS line will be driven high when not active so it doesn't need a pull-up.
- Standoffs are a good idea, I think I can use some adhesive rubber ones
- Damn can't believe its already 2023

**Comment by rdakhil** [comment]
hil board:
- you've got some power signal loops around your fuse F2 pins, I would recommend either turning those areas into a polygon or removing the trace that directly connects the two pins
Screen Shot 2023-05-17 at 1 00 39 AM


input board:
- Q1 is very close to the edge of the board, I think you have room to move it to the left enough so that the courtyard is fully within the board outline

output board:
- this board could use more GND vias/better placement of them, especially closer to your filter capacitors. for example C3's GND via is a bit far from the pad. it wouldn't hurt to put some close to your resistor GND pads too, just to always ensure a shorter return path. the vias are tented by default so I think it's fine if you place your vias a bit closer to the pads (almost touching the pad).
this is not a huge problem for what this board is doing/operating at, but I like to be safer with these kinds of things when vias are free and there is space (and it is good practice)


for all boards: 
- how big are the adhesive standoffs, have you checked they will fit on the boards? I think even if you are going to use adhesive standoffs it might still be a good idea to show the placement in silkscreen (or in user.drawings or something) just to make sure they will actually fit. the input and output boards are quite small

**Review by JasonBrave — COMMENTED** [review]
HIL board:
Does the VIA at right side of J39 have any purpose, there is already a via at left of J39 for connecting ground. Are duplicate vias intentional?
Via D17 at right side of J26 label is a right angle, same for via below J28 label

Analog input board and Output board: LGTM

**Comment by BluCodeGH** [comment]
This has been ordered, merging.

**Pull request merged**
